spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  flyway:
    baseline-on-migrate: true
  cloud:
    azure:
      servicebus:
        connection-string: Endpoint=sb://springintegrationservicebus.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=zTJQHjseaf/OIJbwC3rIFBaCvDKOahI6MLFJGjgw3E0=

server:
  port: 8085
activemq:
  broker-url: tcp://localhost:61616?randomize=false&timeout=10000
  user: admin
  password: password
